In [7]:
import numpy as np
matrix = np.random.randint(1,10,size=4)
print("Original matrix:", matrix)
print("Addition:",matrix+2)
print("Subtraction:",matrix-2)
print("Multiplication:",matrix*2)



Original matrix: [7 7 7 7]
Addition: [9 9 9 9]
Subtraction: [5 5 5 5]
Multiplication: [14 14 14 14]


In [16]:
import numpy as np
array1 = np.random.randint(1,10 ,size = (2,2))
array2 = np.random.randint(1,20 ,size = (2,2))
print("Addition:\n",array1 + array2)
print("Subtraction:\n",array1 - array2)
print("Multiplication:\n",array1 * array2)

Addition:
 [[15 10]
 [24 17]]
Subtraction:
 [[ -5  -6]
 [-12 -13]]
Multiplication:
 [[ 50  16]
 [108  30]]


### mathematical operation

In [25]:
import numpy as np
array1 = np.random.randint(1,10 ,size = (4,4))
print("sum:",np.sum(array1))
print("max:",np.max(array1))
print("min:",np.min(array1))
print("min:",np.prod(array1))


sum: 66
max: 8
min: 1
min: 387072000


In [29]:
# arr = np.array([1,2,3,4,5])
# wts = np.array([4,3,2,1])
# print(arr)
# print(wts)
# print(np.average(arr,weight=wts))

[1 2 3 4 5]
[4 3 2 1]


TypeError: average() got an unexpected keyword argument 'weight'

In [36]:
arr = np.array([1,2,3,4,5])
print(np.percentile(50 ,arr))
print(np.var(arr))
print(np.std(arr))

[50. 50. 50. 50. 50.]
2.0
1.4142135623730951


In [41]:
import numpy as np
matrix = np.random.randint(1,10,size=(3,3))
print(matrix)
print("Sum of columns:",np.sum(matrix,axis=0))
print("Sum of rows:",np.sum(matrix,axis=1))

[[4 2 6]
 [9 4 4]
 [8 9 9]]
Sum of columns: [21 15 19]
Sum of rows: [12 17 26]


In [48]:
arr1 = np.random.randint(1,10,size=(2))
arr2 = np.random.randint(1,10,size=(2))
print(arr1)
print(arr2)
print(np.equal(arr1,arr2))
print(np.not_equal(arr1,arr2))



[6 7]
[4 1]
[False False]
[ True  True]


In [50]:
arr = np.array([1,2,3,4,4,4,4,4,4])
t1 = np.where(arr == 4)
print(t1)

(array([3, 4, 5, 6, 7, 8], dtype=int64),)


In [51]:
arr = np.array([1,2,3,4,4,4,4,4,4])
t1 = np.where(arr%2==1,True , False)
print(t1)

[ True False  True False False False False False False]


In [53]:
arr = np.random.randint(1,10,size=2)
t1 = np.where(arr%2==1 , True , False)
print(t1)

[ True False]


In [74]:
array1 = np.random.randint(1,10,size=(5,5))
print("Actual matrix:\n",array1)
# print("Reverse of a row:",array1[:1,::-1])     
print("Reverse of row:\n",array1[::-1,:])     
print("Reverse of row:\n",array1[2::2,0::2])    

Actual matrix:
 [[9 4 2 4 8]
 [3 8 9 4 6]
 [1 9 6 9 6]
 [7 1 9 9 9]
 [9 5 3 3 2]]
Reverse of row:
 [[9 5 3 3 2]
 [7 1 9 9 9]
 [1 9 6 9 6]
 [3 8 9 4 6]
 [9 4 2 4 8]]
Reverse of row:
 [[1 6 6]
 [9 3 2]]


In [ ]:
4
7349
3
2
3241
24
7. reverse of rows
22

In [2]:
import numpy as np
arr = np.random.randint(1,101, size = 10)
print(arr)
print(arr[(arr%2==0) & (arr>50)])

[ 92  71  35  17 100  99  36  84   1  12]
[ 92 100  84]


In [12]:
matrix1 = np.random.randint(1,50,size = (5,5))
print("Original Rows\n",matrix1)
mask = [
    True,
    False,
    True,
    True,
    False
]
arr2 = matrix1[mask]
print("masked rows\n",arr2)

Original Rows
 [[19  3 25 34  3]
 [32 23 36 24  7]
 [19 18 46 36  5]
 [29 26 16 34 41]
 [ 3 10 20 24 19]]
masked rows
 [[19 25 34]
 [32 36 24]
 [19 46 36]
 [29 16 34]
 [ 3 20 24]]


In [30]:
matrix1 = np.random.randint(1,50,size = (5,5))
print("Original Rows:\n",matrix1)
mask = [
    False,
    True,
    True,
    True,
    False
]
arr2 = matrix1[mask][:,mask]
print("masked columns:\n",arr2)

Original Rows:
 [[30 19  5  4 23]
 [26 17 39  8 48]
 [ 5 38 38 22 33]
 [16 29  4 14 24]
 [38 41 45 25 10]]
masked columns:
 [[17 39  8]
 [38 38 22]
 [29  4 14]]
